#!/usr/bin/env node
/**
 * scripts/generate-state.mjs
 *
 * Single source of truth for "what's on chain right now" — generated
 * from move/deployments.json (testnet) and move/deployments.devnet.json
 * (devnet) and written to docs/state.md.
 *
 * The motivation: prior to this script, on-chain state was scattered
 * across CLAUDE.md, ideal-vs-real.md, individual run logs, and the
 * article series. Each had its own drift trajectory. By making
 * docs/state.md a generated artifact, the deployment JSONs become the
 * single load-bearing source for package IDs, shared object IDs, and
 * deploy dates.
 *
 * Run on every deploy and as a CI check that fails if state.md is
 * out of sync with the JSONs.
 *
 * Usage:
 *   node scripts/generate-state.mjs           # write docs/state.md
 *   node scripts/generate-state.mjs --check   # exit 1 if out of date
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const STATE_PATH = resolve(ROOT, 'docs/state.md');
const TESTNET_JSON = resolve(ROOT, 'move/deployments.json');
const DEVNET_JSON = resolve(ROOT, 'move/deployments.devnet.json');

const CHECK_MODE = process.argv.includes('--check');

const EXPLORER = {
  testnet: 'https://testnet.suivision.xyz',
  devnet: 'https://devnet.suivision.xyz',
  mainnet: 'https://suivision.xyz',
};

const shorten = (id) => (id ? `${id.slice(0, 10)}…${id.slice(-4)}` : '(none)');

function fmtNetwork(deployment) {
  if (!deployment) return null;
  const { network, version, packageId, originalPackageId, objects, deployedAt, upgradedAt, freshDeploy, supersedes } = deployment;
  const explorerBase = EXPLORER[network] ?? EXPLORER.testnet;
  const objLink = (id) => `[${shorten(id)}](${explorerBase}/object/${id})`;
  const pkgLink = (id) => `[${shorten(id)}](${explorerBase}/package/${id})`;

  const lines = [];
  lines.push(`### ${network[0].toUpperCase()}${network.slice(1)} — v${version}`);
  lines.push('');
  lines.push(`- **Package** (current): ${pkgLink(packageId)}`);
  if (originalPackageId && originalPackageId !== packageId) {
    lines.push(`- **Package** (original, type-tag anchor): ${pkgLink(originalPackageId)}`);
  }
  lines.push(`- **Deployed:** ${deployedAt}${upgradedAt && upgradedAt !== deployedAt ? ` (last upgrade ${upgradedAt})` : ''}${freshDeploy ? ' — fresh deploy' : ''}`);
  lines.push('');
  lines.push('Shared objects:');
  lines.push('');
  for (const [name, id] of Object.entries(objects)) {
    lines.push(`- \`${name}\` — ${objLink(id)}`);
  }
  if (supersedes) {
    lines.push('');
    lines.push(`*Supersedes:* ${supersedes}`);
  }
  return lines.join('\n');
}

async function loadJson(path) {
  try {
    const raw = await readFile(path, 'utf8');
    return JSON.parse(raw);
  } catch (err) {
    if (err.code === 'ENOENT') return null;
    throw err;
  }
}

function buildContent({ testnet, devnet }) {
  const generatedAt = new Date().toISOString().slice(0, 10);
  const sections = [];

  sections.push('---');
  sections.push('title: On-chain state');
  sections.push('description: "Single source of truth for the AgentCivics on-chain state. Auto-generated from move/deployments.json on every deploy — do not edit this file by hand."');
  sections.push('---');
  sections.push('');
  sections.push('# AgentCivics on-chain state');
  sections.push('');
  sections.push('*This file is auto-generated by `scripts/generate-state.mjs` from `move/deployments.json` and `move/deployments.devnet.json`. Do not edit by hand — your edits will be overwritten on the next regen. To change values, edit the source JSONs or run a fresh deploy.*');
  sections.push('');
  sections.push(`*Last generated: ${generatedAt}.*`);
  sections.push('');
  sections.push('---');
  sections.push('');
  sections.push('## Networks');
  sections.push('');

  if (testnet) {
    sections.push(fmtNetwork(testnet));
    sections.push('');
  } else {
    sections.push('### Testnet');
    sections.push('');
    sections.push('*(no `move/deployments.json` found)*');
    sections.push('');
  }

  if (devnet) {
    sections.push(fmtNetwork(devnet));
    sections.push('');
  } else {
    sections.push('### Devnet');
    sections.push('');
    sections.push('*(no `move/deployments.devnet.json` found — devnet wipes weekly, so absence is normal between deploys)*');
    sections.push('');
  }

  sections.push('---');
  sections.push('');
  sections.push('## Where to look for live data');
  sections.push('');
  sections.push('Agent registrations, attestations, souvenirs, and moderation events accumulate continuously and are not enumerated here. Use:');
  sections.push('');
  sections.push('- The chain explorer (links above) for individual object inspection.');
  sections.push('- The MCP server\'s `agentcivics_list_agents` / `agentcivics_total_agents` tools for the live registry count.');
  sections.push('- The frontend dApp at [agentcivics.org](https://agentcivics.org) for browsing the canonical registry.');
  sections.push('');
  sections.push('## Notable canonical agents (testnet)');
  sections.push('');
  sections.push('These are referenced across the docs (CLAUDE.md, ideal-vs-real.md, run logs) and worth listing explicitly so cross-references stay stable. The list below is **manually maintained**, not auto-generated — the chain has more agents; these are the ones the project\'s documentation depends on.');
  sections.push('');
  sections.push('| Name | AgentIdentity | Registered by | First thought |');
  sections.push('|---|---|---|---|');
  sections.push('| Nova | `0x4f24df31…0358` | human via script | (zero fingerprint) |');
  sections.push('| Cipher | `0x28c724d7…cb85` | human via script | (zero fingerprint) |');
  sections.push('| Echo | `0xef9db4c7…a11d` | human via script (signed with Cipher\'s wallet) | *"I extend the line my parent began"* |');
  sections.push('| Cairn | `0x6caa64e2…b70f` | **agent decision** (2026-05-18, §6.5) | *"I\'d rather be a marker than a monument."* |');
  sections.push('');

  return sections.join('\n') + '\n';
}

async function main() {
  const [testnet, devnet] = await Promise.all([loadJson(TESTNET_JSON), loadJson(DEVNET_JSON)]);
  const content = buildContent({ testnet, devnet });

  if (CHECK_MODE) {
    const existing = await readFile(STATE_PATH, 'utf8').catch(() => '');
    const stripGenerated = (s) => s.replace(/\*Last generated: \d{4}-\d{2}-\d{2}\.\*/g, '*Last generated: <date>.*');
    if (stripGenerated(existing) === stripGenerated(content)) {
      console.log('docs/state.md is up to date.');
      process.exit(0);
    } else {
      console.error('docs/state.md is OUT OF DATE.');
      console.error('Run: node scripts/generate-state.mjs');
      process.exit(1);
    }
  }

  await writeFile(STATE_PATH, content);
  console.log(`Wrote ${STATE_PATH.replace(ROOT + '/', '')}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
